set nocompatible
filetype plugin indent on

set modelines=1

"Set to auto read when a file is changed from the outside
set autoread

"Have the mouse enabled all the time:
set mouse=a


" 显示行号
set nu

set cursorline
set shiftround
set linebreak
let &showbreak='↪ '

set showcmd "show incomplete cmds down the bottom
set showmode "show current mode down the bottom

set ignorecase
set incsearch "find the next match as we type the search
set hlsearch "hilight searches by default
set smartcase

set wildmenu
set completeopt=longest,menuone
set splitbelow

set sessionoptions-=options

"set nowrap
" wrapping text
set wrap linebreak

set laststatus=2

" 默认禁用代码折叠
set nofoldenable
"选择代码折叠类型
"set foldmethod=syntax
"启动vim时不要自动折叠代码
set foldlevel=100

set wildignore+=*.o,.git,.svn,*.jpg,*.gif,*.png,*.swf,*.psd,*.rar,*.zip,*.doc


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Fileformats
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" 编码设定
set encoding=utf-8
set fileencodings=utf-8,ucs-bom,gbk,gb2312,gb18030,cp936,default,latin1


" 打开代码高亮
syntax enable

" 将F2键映射为取消字符串搜索后的高亮
map <F2> :nohlsearch<CR>

" omni
" Add a C-p is for cancel select first item, this issue is cased by NeoComplCache.
imap <C-L> <C-x><C-o><C-p>


" 打开文件即切换到文件所在目录
set autochdir

" ctrl v 从剪切板中粘贴
cmap <C-V>              <C-R>+
exe 'inoremap <script> <C-V>' paste#paste_cmd['i']
exe 'vnoremap <script> <C-V>' paste#paste_cmd['v']
imap <S-Insert>         <C-V>
vmap <S-Insert>         <C-V>

" Ctrl c 复制到剪切板
vnoremap <C-C> "+y

nmap j gj
nmap k gk

" move on windows
map <C-I> <C-W>k
map <C-J> <C-W>j
map <C-H> <C-W>h
map <C-L> <C-W>l

" windows move
set winaltkeys=no
map <A-k> <C-W>K
map <A-j> <C-W>J
map <A-h> <C-W>H
map <A-l> <C-W>L


"Turn backup off
set nobackup
set nowb
set noswapfile

" tab
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

"Auto indent
set ai

"Smart indet
set si
au BufRead *.blade.php setlocal ts=2 sts=2 sw=2


" yaml,xml,html 使用2个空格作为缩进
autocmd FileType html,xhtml,htmldjango,css,scss,less,xml,jsp setlocal ts=2 sts=2 sw=2 expandtab
